name: Elasticist Dev Check

on:
  push:
  pull_request:
    types: [ opened, reopened ]

env:
  CARGO_TERM_COLOR: always

jobs:
  base:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
