name: Elasticist Dev Check

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  base:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        run: cargo clippy -- -D clippy::suspicious -D clippy::style -W clippy::pedantic

      - name: Build
        run: cargo build --features deny-warnings

      - name: Run tests
        run: cargo test --verbose
